= AsciiDoc examples
ifdef::env-github[]
// GitHub Flavored AsciiDoc (GFA) specific content
// Alternative to `:icons: font` on GitHub.
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
// End of GFA-specific content
endif::[]
ifndef::env-github[]
// Content for AsciiDoc (not GFA)
\:icons: font
// End of AsciiDoc-specific content
endif::[]

== GitHub Actions
Example of actions to generate document.

* Base docker images
** Base: https://github.com/asciidoctor/docker-asciidoctor
** https://github.com/tonynv/asciidoctor-action[tonynv/asciidoctor-action: GitHub Action to build asciidoc^]

=== Actions

* https://github.blog/news-insights/product-news/github-pages-now-uses-actions-by-default/[GitHub Pages now uses Actions by default - The GitHub Blog^]
* https://github.com/actions/checkout[actions/checkout: Action for checking out a repo^]
* https://github.com/actions/upload-pages-artifact[actions/upload-pages-artifact^] +
  A composite action for packaging and uploading an artifact that can be deployed to GitHub Pages.

== GitHub Flavored AsciiDoc

Referring to the link:

* link:https://gist.github.com/dcode/0cfbf2699a1fe9b46ff04c41721dda74[GitHub Flavored AsciiDoc (GFA) Gist^]
* link:https://github.github.com/gfm/[GitHub Flavored Markdown (GFM)^]

=== Functional differences
GitHub Flavored AsciiDoc (GFA) is a dialect of AsciiDoc that is tailored for rendering on GitHub, and it has some functional differences.

* The `include::{startsb}{endsb}` directive is not supported.
* Math blocks within tables are not supported in GFA.

=== Example of writing GFA-specific content

[source,asciidoc]
----
ifdef::env-github{startsb}{endsb}
// GitHub Flavored AsciiDoc (GFA) specific content
// Alternative to `:icons: font` on GitHub.
\:tip-caption: :bulb:
\:note-caption: :information_source:
\:important-caption: :heavy_exclamation_mark:
\:caution-caption: :fire:
\:warning-caption: :warning:
// End of GFA-specific content
endif::{startsb}{endsb}
ifndef::env-github{startsb}{endsb}
// Content for AsciiDoc (not GFA)
\:icons: font
// End of AsciiDoc-specific content
endif::{startsb}{endsb}
----

=== Escape characters
In GFA, the backslash (`\`) is used as an escape character. To include a literal backslash in your content, you need to escape it with another backslash. For example, to include a single backslash, you would write `\\`.

* dollar sign: Price is `\$100`
* backslash: `\\`
* curly braces: `\{` and `\}`

=== Admonition blocks
Admonition blocks are used to highlight important information, tips, warnings, etc. They can be created using the following syntax:

[source,asciidoc]
----
NOTE: This is a note.

TIP: This is a tip.

IMPORTANT: This is important.

CAUTION: This is a caution.

WARNING: This is a warning.
----

NOTE: This is a note.

TIP: This is a tip.

IMPORTANT: This is important.

CAUTION: This is a caution.

WARNING: This is a warning.

=== Math equations examples

AsciiDoc and GitHub Flavored AsciiDoc (GFA) are not compatible for writing mathematical formulas.

The correspondence between GFA syntax and AsciiDoc syntax is as follows.

[cols="1,1,1"]
|===
h| AsciiDoc syntax
h| GFA syntax
h| Rendered

| latexmath:{startsb}x^2{endsb}
| `$x^2$`
| $x^2$

| The total cost is latexmath:{startsb}100\${endsb}
| The total cost is `$100\text{\$}$`
| The total cost is $100\text{\$}$

|
{startsb}stem,latexmath{endsb} +
{plus}{plus}{plus}{plus} +
y=x^2 +
{plus}{plus}{plus}{plus}
|
{startsb}source,math{endsb} +
---- +
y=x^2 +
----
|
[source,math]
----
y=x^2
----
|===

==== Math equation with sidebar
We can use the math equation in a sidebar.

.Sidebar Title (Optional)
****
[source,math]
----
y = x^2
----
****

==== Example: Sigmoid function

The sigmoid function $\sigma(x) = \frac{1}{1 + e^{-x}}$ is commonly used in neural networks. The range of the sigmoid function( $\sigma(x)$ ) is $[0, 1]$.

[source,math]
----
\begin{aligned}
\sigma(x) &= \frac{1}{1 + e^{-x}} \\
\sigma'(x) &= \sigma(x)\left(1 - \sigma(x)\right)
\end{aligned}
----
