hide empty description
skinparam shadowing false
skinparam arrow {
  Color black
}
skinparam state {
  BorderColor transparent
  BackgroundColor transparent
  Padding 0
}

left to right direction

state "**V**" as V1
state "**V**" as V2
state "**V**" as V3

V1 --> V2 : S
V2 --> V3 : T
V2 --> V1 : S<sup>-1</sup>
V3 --> V2 : T<sup> -1</sup>
V1 --> V3 : TS
V3 --> V1 : (TS)<sup>-1</sup>