ifndef::leveloffset[]
:toc: left
:stem:
:toclevels: 3
endif::[]

:bl: pass:p[ +]

:xx: ×
:cdot: ·
:circ: &#8728;
:cong: &#8773;
:oplus: ⊕
:forall: ∀
:exists: ∃
:cap: &#8745;
:cup: ∪
:isin: &#8712;
:ni: ∋
:neq: ≠
:leq: &#8804;
:emptyset: ∅
:subset: ⊂
:supset: ⊃
:sube: ⊆
:supe: ⊇
:isomorphic: ≅

ifeval::["{backend}" != "pdf"]
:implies: pass:q[```⟹```]
:impliedby: ⟸
:iff: ⟺
:longmapsto: pass:q,r[&#10236;]
:qed: ∎
:vdots: ⋮
endif::[]

ifeval::["{backend}" == "pdf"]
:implies: =>
:impliedby: <=
:iff: ⇔
:longmapsto: ->
:qed: ■
:vdots: :
endif::[]

ifndef::leveloffset[]
:stem: latexmath
endif::[]

== Mathematical symbols

.References
* https://www.fileformat.info/info/unicode/block/mathematical_operators/list.htm[Unicode Characters in the Mathematical Operators Block]
* https://qiita.com/minfuk/items/0bd1ffa20b44759d486e[TeXの数式記号とUnicodeのマッピング（途中） - Qiita]
* U+2200
** https://www.compart.com/en/unicode/block/U+2200[Unicode Block “Mathematical Operators”^]
** https://www.fileformat.info/info/unicode/block/mathematical_operators/list.htm[Unicode Characters in the Mathematical Operators Block]
* https://www.compart.com/en/unicode/block/U+25A0[Unicode Block “Geometric Shapes”^]
* https://www.compart.com/en/unicode/block/U+27F0[Unicode Block “Supplemental Arrows-A”^]
* https://www.compart.com/en/unicode/block/U+2A00[Unicode Block “Supplemental Mathematical Operators”^]
* http://detexify.kirelabs.org/classify.html[Detexify LaTeX handwritten symbol recognition^]

=== Brackets

.General punctuation
[cols="2a,3a,^.^1a,^.^1a,6a" {table_options}]
|===
2+h| Type                               2+h| Rendered                          h|
h| HTML Entity                 h| Tex Alt h| HTML      h| LaTeX                h| Character name



>|  `\&#x28;` {bl}    `\&#40;` |           |     &#40; |                     | Left Parenthesis
>|  `\&#x29;` {bl}    `\&#41;` |           |     &#41; |                     | Right Parenthesis
>|  `\&#x7D;` {bl}   `\&#125;` | `\rbrace` |    &#125; | latexmath:[\rbrace] | Right Curly Bracket
>|  `\&#x7B;` {bl}   `\&#123;` | `\lbrace` |    &#123; | latexmath:[\lbrace] | Left Curly Bracket
>|  `\&#x5B;` {bl}    `\&#91;` | `\lbrack` |     &#91; | latexmath:[\lbrack] | Left Square Bracket
>|  `\&#x5D;` {bl}    `\&#93;` | `\rbrack` |     &#93; | latexmath:[\rbrack] | Right Square Bracket
>| `\&#x27E8;`{bl} `\&#10216;` | `\langle` |  &#10216; | latexmath:[\langle] | Mathematical Left Angle Bracket
>| `\&#x27E9;`{bl} `\&#10217;` | `\rangle` |  &#10217; | latexmath:[\rangle] | Mathematical Right Angle Bracket
>| `\&#x3008;`{bl} `\&#12296;` |           |  &#12296; |                     | Left Angle Bracket
>| `\&#x3009;`{bl} `\&#12297;` |           |  &#12297; |                     | Right Angle Bracket
|===

=== Operation symbols

.Operation symbols
[cols="2a,3a,1a,1a,6a" {table_options}]
|===
2+h| Type                                     2+h| Rendered                           h|
h| HTML Entity                 h| Tex Alt       h| HTML    h| LaTeX                   h| Character name

>|   `\&#xD7;` {bl}   `\&#215;` | `\times`       |   &#215; | latexmath:[\times]       | Multiplication Sign
>|   `\&#xF7;` {bl}   `\&#247;` | `\div`         |   &#247; | latexmath:[\div]         | Division Sign
>| `\&#x2217;` {bl}  `\&#8727;` | `\ast`         |  &#8727; | latexmath:[\ast]         | Asterisk Operator
>| `\&#x2218;` {bl}  `\&#8728;` | `\circ`        |  &#8728; | latexmath:[\circ]        | Ring Operator
>| `\&#x25EF;` {bl}  `\&#9711;` | `\bigcirc`     |  &#9711; | latexmath:[\bigcirc]     | Large Circle
>| `\&#x2219;` {bl}  `\&#8729;` | `\bullet`      |  &#8729; | latexmath:[\bullet]      | Bullet Operator
>| `\&#x00B1;` {bl}   `\&#177;` | `\pm`          |   &#177; | latexmath:[\pm]          | Plus-Minus Sign
>| `\&#x2213;` {bl}  `\&#8723;` | `\mp`          |  &#8723; | latexmath:[\mp]          | Minus-or-Plus Sign
>| `\&#x2207;` {bl}  `\&#8711;` | `\nabla`       |  &#8711; | latexmath:[\nabla]       | Nabla
>| `\&#x2240;` {bl}  `\&#8768;` | `\wr`          |  &#8768; | latexmath:[\wr]          | Wreath Product
>| `\&#x2295;` {bl}  `\&#8853;` | `\oplus`       |  &#8853; | latexmath:[\oplus]       | Circled Plus
>| `\&#x2296;` {bl}  `\&#8854;` | `\ominus`      |  &#8854; | latexmath:[\ominus]      | Circled Minus
>| `\&#x2297;` {bl}  `\&#8855;` | `\otimes`      |  &#8855; | latexmath:[\otimes]      | Circled Times
>| `\&#x2298;` {bl}  `\&#8856;` | `\oslash`      |  &#8856; | latexmath:[\oslash]      | Circled Division Slash
>| `\&#x2299;` {bl}  `\&#8857;` | `\odot`        |  &#8857; | latexmath:[\odot]        | Circled Dot Operator
>| `\&#x229A;` {bl}  `\&#8858;` | `\circledcirc` |  &#8858; | latexmath:[\circledcirc] | Circled Ring Operator
>| `\&#x229B;` {bl}  `\&#8859;` | `\circledast`  |  &#8859; | latexmath:[\circledast]  | Circled Asterisk Operator
>| `\&#x229D;` {bl}  `\&#8861;` | `\circleddash` |  &#8861; | latexmath:[\circleddash] | Circled Dash
>| `\&#x229E;` {bl}  `\&#8862;` | `\boxplus`     |  &#8862; | latexmath:[\boxplus]     | Squared Plus
>| `\&#x229F;` {bl}  `\&#8863;` | `\boxminus`    |  &#8863; | latexmath:[\boxminus]    | Squared Minus
>| `\&#x22A0;` {bl}  `\&#8864;` | `\boxtimes`    |  &#8864; | latexmath:[\boxtimes]    | Squared Times
>| `\&#x22A1;` {bl}  `\&#8865;` | `\boxdot`      |  &#8865; | latexmath:[\boxdot]      | Squared Dot Operator
>| `\&#x22C5;` {bl}  `\&#8901;` | `\cdot`        |  &#8901; | latexmath:[\cdot]        | Dot Operator
>| `\&#x22C6;` {bl}  `\&#8902;` | `\star`        |  &#8902; | latexmath:[\star]        | Star Operator
>| `\&#x22C8;` {bl}  `\&#8904;` | `\bowtie` or `\Join`
                                                 |  &#8904; | latexmath:[\Join]        | Bowtie
>| `\&#x22C9;` {bl}  `\&#8905;` | `\ltimes`      |  &#8905; | latexmath:[\ltimes]      | Left Normal Factor Semidirect Product
>| `\&#x22CA;` {bl}  `\&#8906;` | `\rtimes`      |  &#8906; | latexmath:[\rtimes]      | Right Normal Factor Semidirect Product
>| `\&#x2227;` {bl}  `\&#8743;` | `\wedge`       |  &#8743; | latexmath:[\wedge]       | Logical And
>| `\&#x2228;` {bl}  `\&#8744;` | `\vee`         |  &#8744; | latexmath:[\vee]         | Logical Or
>| `\&#x22C0;` {bl}  `\&#8896;` | `\bigwedge`    |  &#8896; | latexmath:[\bigwedge]    | N-Ary Logical And
>| `\&#x22C1;` {bl}  `\&#8897;` | `\bigvee`      |  &#8897; | latexmath:[\bigvee]      | N-Ary Logical Or
>| `\&#x007C;` {bl}  `\&#0124;` | `\mid` or `\middle`
                                                 |   {vbar} | latexmath:[\mid]         | Vertical Line
>| `\&#x2016;` {bl}  `\&#8214;` | `{backslash}{vbar}` or `\Arrowvert`
                                                 |  &#8214; | latexmath:[\Arrowvert]   | Double Vertical Line
|===

=== Relation symbols

==== Equals sign

.Equals sign
[cols="^.^6a,9a,^.^3a,^.^3a,17a" {table_options}]
|===
2+h| Type                                      2+h| Rendered                             h|
h| HTML Entity                h| Tex Alt         h| HTML    h| LaTeX                     h| Character name

| `\&#x003D;` {bl}  `\&#0061;` |                  |        = | latexmath:[=]              | Equals Sign
| `\&#xA78A;` {bl} `\&#42890;` |                  | &#42890; |                            | Modifier Letter Short Equals Sign
| `\&#xFF1D;` {bl} `\&#65309;` |                  | &#65309; |                            | Fullwidth Equals Sign
| `\&#x2260;` {bl}  `\&#8800;` | `\ne`            |  &#8800; | latexmath:[\ne]            | Not Equal To
| `\&#x223C;` {bl}  `\&#8764;` | `\sim`           |  &#8764; | latexmath:[\sim]           | Tilde Operator
| `\&#x223D;` {bl}  `\&#8765;` | `\backsim`       |  &#8765; | latexmath:[\backsim]       | Reversed Tilde
| `\&#x2241;` {bl}  `\&#8769;` | `\nsim`          |  &#8769; | latexmath:[\nsim]          | Not Tilde
| `\&#x2243;` {bl}  `\&#8771;` | `\simeq`         |  &#8771; | latexmath:[\simeq]         | Asymptotically Equal To
| `\&#x2245;` {bl}  `\&#8773;` | `\cong`          |  &#8773; | latexmath:[\cong]          | Approximately Equal To
| `\&#x2248;` {bl}  `\&#8776;` | `\approx`        |  &#8776; | latexmath:[\approx]        | Almost Equal To
| `\&#x224D;` {bl}  `\&#8781;` | `\asymp`         |  &#8781; | latexmath:[\asymp]         | Equivalent To
| `\&#x2250;` {bl}  `\&#8784;` | `\doteq`         |  &#8784; | latexmath:[\doteq]         | Approaches the Limit
| `\&#x2251;` {bl}  `\&#8785;` | `\doteqdot`      |  &#8785; | latexmath:[\doteqdot]      | Geometrically Equal To
| `\&#x2252;` {bl}  `\&#8786;` | `\fallingdotseq` |  &#8786; | latexmath:[\fallingdotseq] | Approximately Equal to or the Image Of
| `\&#x2253;` {bl}  `\&#8787;` | `\risingdotseq`  |  &#8787; | latexmath:[\risingdotseq]  | Image of or Approximately Equal To
| `\&#x2254;` {bl}  `\&#8788;` | `:=`             |  &#8788; | latexmath:[:=]             | Colon Equals
| `\&#x2255;` {bl}  `\&#8789;` | `=:`             |  &#8789; | latexmath:[=:]             | Equals Colon
| `\&#x225C;` {bl}  `\&#8796;` |
[source,latex]
----
\overset{\scriptscriptstyle\Delta}{=}
----
                                                  |  &#8796; | latexmath:[\overset{\scriptscriptstyle\Delta}{=}]
                                                                                          | Delta Equal To
| `\&#x225D;` {bl}  `\&#8797;` |
[source,latex]
----
\overset{\scriptscriptstyle\rm def}{=}
----
                                                  |  &#8797; | latexmath:[\overset{\scriptscriptstyle\rm def}{=}]
                                                                                          | Equal to By Definition
| `\&#x2261;` {bl}  `\&#8801;` | `\equiv`         |  &#8801; | latexmath:[\equiv]         | Identical To
| `\&#x2262;` {bl}  `\&#8802;` | `\not\equiv`     |  &#8802; | latexmath:[\not\equiv]     | Not Identical To
|===

* https://en.wikipedia.org/wiki/Equals_sign[Equals sign - Wikipedia]

==== Inequality
.Inequality
[cols="^.^6a,8a,7a,^.^4a,^.^5a,^.^4a,17a" {table_options}]
|===
3+h| Type                                                3+h| Rendered                                                  h|
h| HTML Entity                h| Tex Alt      h| AsciiMath h| HTML         h| LaTeX                  h| AsciiMath       h| Character name

>| `\&#x3C;` {bl} `\&#60;` {bl} `\&lt;` | `&lt;`  | `<`     |         &lt; | latexmath:[<]            | asciimath:[<]    | Less-Than Sign
>| `\&#x3E;` {bl} `\&#62;` {bl} `\&gt;` | `&gt;`  | `>`     |         &gt; | latexmath:[>]            | asciimath:[>]    | Greater-Than Sign
>| `\&#x221D;` {bl}  `\&#8733;` | `\propto`       | `prop`  |      &#8733; | latexmath:[\propto]      | asciimath:[prop] | Proportional To
>| `\&#x2264;` {bl}  `\&#8804;` | `\le` or `\leq` | `&lt;=` |      &#8804; | latexmath:[\leq]{bl} latexmath:[\leq]
                                                                                                      | asciimath:[<=] | Less-Than or Equal To    
>| `\&#x2265;` {bl}  `\&#8805;` | `\ge` or `\geq` | `&gt;=` |      &#8805; | latexmath:[\geq]{bl} latexmath:[\geq]
                                                                                                      | asciimath:[>=] | Greater-Than or Equal To 
>| `\&#x2266;` {bl}  `\&#8806;` | `\leqq`         |         |      &#8806; | latexmath:[\leqq]        |                | Less-Than Over Equal To
>| `\&#x2267;` {bl}  `\&#8807;` | `\geqq`         |         |      &#8807; | latexmath:[\geqq]        |                | Greater-Than Over Equal To
>| `\&#x226A;` {bl}  `\&#8810;` | `\ll`           |         |  a &#8810; b | latexmath:[a \ll b]      |                | Much Less-Than
>| `\&#x226B;` {bl}  `\&#8811;` | `\gg`           |         |  a &#8811; b | latexmath:[a \gg b]      |                | Much Greater-Than
>| `\&#x226E;` {bl}  `\&#8814;` | `\not\lt` or `\nless` |   |      &#8814; | latexmath:[\not\lt], latexmath:[\nless] | | Not Less-Than
>| `\&#x226F;` {bl}  `\&#8815;` | `\not\gt` or `\ngtr` |    |      &#8815; | latexmath:[\not\gt], latexmath:[\ngtr] |  | Not Greater-Than
>| `\&#x2270;` {bl}  `\&#8816;` | `\nleq`         |         |      &#8816; | latexmath:[\nleq]        |                | Neither Less-Than Nor Equal To
>| `\&#x2271;` {bl}  `\&#8817;` | `\ngeq`         |         |      &#8817; | latexmath:[\ngeq]        |                | Neither Greater-Than Nor Equal To
>| `\&#x2A7D;` {bl} `\&#10877;` | `\leqslant`     |         |     &#10877; | latexmath:[\leqslant]    |                | Less-Than or Slanted Equal To
>| `\&#x2A7E;` {bl} `\&#10878;` | `\geqslant`     |         |     &#10878; | latexmath:[\geqslant]    |                | Greater-Than or Slanted Equal To
>| `\&#x2A87;` {bl} `\&#10887;` | `\nleqslant`    |         |     &#10887; | latexmath:[\nleqslant]   |                | Less-Than and Single-Line Not Equal To
>| `\&#x2A88;` {bl} `\&#10888;` | `\ngeqslant`    |         |     &#10888; | latexmath:[\ngeqslant]   |                | Greater-Than and Single-Line Not Equal To
>| `\&#x2A95;` {bl} `\&#10901;` | `\eqslantless`  |         |     &#10901; | latexmath:[\eqslantless] |                | Slanted Equal to or Less-Than
>| `\&#x2A96;` {bl} `\&#10902;` | `\eqslantgtr`   |         |     &#10902; | latexmath:[\eqslantgtr]  |                | Slanted Equal to or Greater-Than
|===

==== others

.Relation symbols - others
[cols="10d,8d,8d,8a,8a,8a,17a" {table_options}]
|===
3+h| Type                                  3+h| Rendered                                                   |
h| HTML Entity h| TeX alt h| AsciiMath       h| HTML             h| LaTeX              h| AsciiMath       h| Character name

>| `\&#x227A;` | `\prec`   | `-&lt;`          |  [big]##&#8826;## | latexmath:[\prec]   | asciimath:[-<]   | Precedes
>| `\&#x2AAF;` | `\preceq` | `-&lt;=`         | [big]##&#10927;## | latexmath:[\preceq] | asciimath:[-<=]  | Precedes Above Single-Line Equals Sign
>| `\&#x227B;` | `\succ`   | `>-`             |  [big]##&#8827;## | latexmath:[\succ]   | asciimath:[>-]   | Succeeds
>| `\&#x2AB0;` | `\succeq` | `>-=`            | [big]##&#10928;## | latexmath:[\succeq] | asciimath:[>-=]  | Succeeds Above Single-Line Equals Sign
|===

=== Sets

.LaTeX
[cols="^.^6a,^.^8a,^.^7a,^.^4a,^.^6a,^.^4a,16a" {table_options}]
|===
3+h| Type                                                3+h| Rendered                                                              h|
   h| HTML Entity               h| Tex Alt       h| AsciiMath h| HTML            h| LaTeX                     h| AsciiMath          h| Character name

   >| `\&#x2201;`{bl} `\&#8705;` | `\complement`  | `sf "c"`   | _A_^&#8705;^     | latexmath:[A^\complement]  | asciimath:[A^(sf "c")] | Complement
.2+>| `\&#x2205;`{bl} `\&#8709;` | `\emptyset`    | `O/`    .2+| &#8709;          | latexmath:[\emptyset]      | asciimath:[O/]   .2+| Empty Set
                                 | `\varnothing`  |                               | latexmath:[\varnothing]    |
   >| `\&#x2229;`{bl} `\&#8745;` | `\cap`         | `nn`       | [big]##&#8745;## | latexmath:[\cap]           | asciimath:[nn]      | Intersection
   >| `\&#x222A;`{bl} `\&#8746;` | `\cup`         | `uu`       | [big]##&#8746;## | latexmath:[\cup]           | asciimath:[uu]      | Union
   >| `\&#x2208;`{bl} `\&#8712;` | `\in`          | `in`       | [big]##&#8712;## | latexmath:[\in]            | asciimath:[in]      | Element Of
   >| `\&#x2209;`{bl} `\&#8713;` | `\notin`       | `!in`      | [big]##&#8713;## | latexmath:[\notin]         | asciimath:[!in]     | Not An Element Of
   >| `\&#x220B;`{bl} `\&#8715;` | `\ni`          |            | [big]##&#8715;## | latexmath:[\ni]            |                     | Contains as Member
   >| `\&#x220C;`{bl} `\&#8716;` | `\not\ni`      |            | [big]##&#8716;## | latexmath:[\not\ni]        |                     | Does Not Contain as Member
.2+>| `\&#x2216;`{bl} `\&#8726;` | `\backslash`   | +++X\\A+++{bl} `backslash`
                                                            .2+| X&#8726;A        | latexmath:[X \backslash A] | asciimath:[X\\A] .2+| Set Minus
                                 | `\setminus`    | `setminus`                    | latexmath:[X \setminus A]  | asciimath:[X setminus A]
   >| `\&#x2282;`{bl} `\&#8834;` | `\subset`      | `sub`      | [big]##&#8834;## | latexmath:[\subset]        | asciimath:[sub]     | Subset Of
   >| `\&#x2283;`{bl} `\&#8835;` | `\supset`      | `sup`      | [big]##&#8835;## | latexmath:[\supset]        | asciimath:[sup]     | Superset Of
   >| `\&#x2284;`{bl} `\&#8836;` | `\not\subset`  | `cancel(subset)`
                                                               | [big]##&#8836;## | latexmath:[\not\subset]    | asciimath:[cancel(subset)]
                                                                                                                                     | Not A Subset Of
   >| `\&#x2285;`{bl} `\&#8837;` | `\not\supset`  | `cancel(supset)`
                                                               | [big]##&#8837;## | latexmath:[\not\supset]    | asciimath:[cancel(supset)]
                                                                                                                                     | Not A Superset Of
   >| `\&#x2286;`{bl} `\&#8838;` | `\subseteq`    | `sube`     | [big]##&#8838;## | latexmath:[\subseteq]      | asciimath:[sube]    | Subset of or Equal To
   >| `\&#x2287;`{bl} `\&#8839;` | `\supseteq`    | `supe`     | [big]##&#8839;## | latexmath:[\supseteq]      | asciimath:[supe]    | Superset of or Equal To
   >| `\&#x2288;`{bl} `\&#8840;` | `\nsubseteq`   |            | [big]##&#8840;## | latexmath:[\nsubseteq]     |                     | Neither A Subset of Nor Equal To
   >| `\&#x2289;`{bl} `\&#8841;` | `\nsupseteq`   |            | [big]##&#8841;## | latexmath:[\nsupseteq]     |                     | Neither A Superset of Nor Equal To
   >| `\&#x228A;`{bl} `\&#8842;` | `\subsetneq`   |            | [big]##&#8842;## | latexmath:[\subsetneq]     |                     | Subset of with Not Equal To
   >| `\&#x228B;`{bl} `\&#8843;` | `\supsetneq`   |            | [big]##&#8843;## | latexmath:[\supsetneq]     |                     | Superset of with Not Equal To
|===

.Triangle
[cols="^.^6a,^.^8a,^.^4a,^.^5a,17a" {table_options}]
|===
2+h| Type                                     2+h| Rendered                             h|
h| HTML Entity                h| Tex Alt        h| HTML    h| LaTeX                     h| Character name

>| `\&#x22b2;`{bl} `\&#8882;` | `\triangleleft`  |  &#8882; | latexmath:[\triangleleft]  | Normal Subgroup Of
>| `\&#x22b3;`{bl} `\&#8883;` | `\triangleright` |  &#8883; | latexmath:[\triangleright] | Contains as Normal Subgroup
>| `\&#x22b4;`{bl} `\&#8884;` |                  |  &#8884; |                            | Normal Subgroup of or Equal To
>| `\&#x22b5;`{bl} `\&#8885;` |                  |  &#8885; |                            | Contains as Normal Subgroup or Equal To
>| https://www.compart.com/en/unicode/U+25C1[`\&#x25C1;`^]{bl} `\&#9665;`
                              |                  |  &#9665; |                            | White Left-Pointing Triangle
>| https://www.compart.com/en/unicode/U+25C3[`\&#x25C3;`^]{bl} `\&#9667;`
                              | `\triangleleft`  |  &#9667; | latexmath:[\triangleleft]  | White Left-Pointing Small Triangle
>| https://www.compart.com/en/unicode/U+25B7[`\&#x25B7;`^]{bl} `\&#9655;`
                              |                  |  &#9655; |                            | White Right-Pointing Triangle
>| https://www.compart.com/en/unicode/U+25B9[`\&#x25B9;`^]{bl} `\&#9657;`
                              | `\triangleright` |  &#9657; | latexmath:[\triangleright] | White Right-Pointing Small Triangle
|===

=== Logical symbols

.Logical symbols
[cols="^.^6a,8a,^.^4a,^.^4a,17a" {table_options}]
|===
2+h| Type                                     2+h| Rendered                             h|
h| HTML Entity                h| Tex Alt        h| HTML      h| LaTeX                   h| Character name

| http://www.fileformat.info/info/unicode/char/2227/index.htm[`\&#x2227;`] {bl} `\&#8743;`
                               | `\land`         |  &#8743; | latexmath:[\land]          | Logical And
| http://www.fileformat.info/info/unicode/char/2228/index.htm[`\&#x2228;`] {bl} `\&#8744;`
                               | `\lor`          |  &#8744; | latexmath:[\lor]           | Logical Or
| `\&#x00AC;` {bl}  `\&#172;`  | `\neg`          |   &#172; | latexmath:[\neg]           | Not Sign
| `\&#x2200;` {bl}  `\&#8704;` | `\forall`       |  &#8704; | latexmath:[\forall]        | For All
| `\&#x2203;` {bl}  `\&#8707;` | `\exists`       |  &#8707; | latexmath:[\exists]        | There Exists
| `\&#x2204;` {bl}  `\&#8708;` | `\nexists`      |  &#8708; | latexmath:[\nexists]       | There Does Not Exist
| `\&#x2234;` {bl}  `\&#8756;` | `\therefore`    |  &#8756; | latexmath:[\therefore]     | Therefore
| `\&#x2235;` {bl}  `\&#8757;` | `\because`      |  &#8757; | latexmath:[\because]       | Because
| `\&#x22A2;` {bl}  `\&#8866;` | `\vdash`        |  &#8866; | latexmath:[\vdash]         | Right Tack
| `\&#x22A4;` {bl}  `\&#8868;` | `\top`          |  &#8868; | latexmath:[\top]           | Down Tack
| `\&#x22A8;` {bl}  `\&#8872;` | `\models`       |  &#8872; | latexmath:[\models]        | True
| `\&#x27F8;` {bl} `\&#10232;` | `\impliedby`    | &#10232; | latexmath:[\impliedby]     | Long Leftwards Double Arrow
| `\&#x27F9;` {bl} `\&#10233;` | `\implies`      | &#10233; | latexmath:[\implies]       | Long Rightwards Double Arrow
| `\&#x27FA;` {bl} `\&#10234;` | `\iff`{bl} `\Longleftrightarrow`
                                                 | &#10234; | latexmath:[\iff]           | Long Left Right Double Arrow
|===

=== Sum-class symbol
.Sum-class symbol
[cols="^.^6a,8a,8a,^.^4a,^.^4a,^.^4a,17a" {table_options}]
|===
3+h| Type                                                3+h| Rendered                                                h|
h| HTML Entity                h| Tex Alt     h| AsciiMath  h| HTML             h| LaTeX                 h| AsciiMath  h| Character name

>| `\&#x220F;`{bl}  `\&#8719;` | `\prod`      | `prod`      |  [big]##&#8719;## | latexmath:[\prod]      | asciimath:[prod] | N-Ary Product
>| `\&#x2210;`{bl}  `\&#8720;` | `\coprod`    |             |  [big]##&#8720;## | latexmath:[\coprod]    |                  | N-Ary Coproduct
>| `\&#x2211;`{bl}  `\&#8721;` | `\sum`       | `sum`       |  [big]##&#8721;## | latexmath:[\sum]       | asciimath:[sum]  | N-Ary Summation
>| `\&#x222B;`{bl}  `\&#8747;` | `\int`       | `int`       |  [big]##&#8747;## | latexmath:[\int]       | asciimath:[int]  | Integral
>| `\&#x222E;`{bl}  `\&#8750;` | `\oint`      | `oint`      |  [big]##&#8750;## | latexmath:[\oint]      | asciimath:[oint] | Contour Integral
>| `\&#x22C0;`{bl}  `\&#8896;` | `\bigwedge`  | `^^^`       |  [big]##&#8896;## | latexmath:[\bigwedge]  | asciimath:[^^^]  | N-Ary Logical And
>| `\&#x22C1;`{bl}  `\&#8897;` | `\bigvee`    | `vvv`       |  [big]##&#8897;## | latexmath:[\bigvee]    | asciimath:[vvv]  | N-Ary Logical Or
>| `\&#x22C2;`{bl}  `\&#8898;` | `\bigcap`    | `nnn`       |  [big]##&#8898;## | latexmath:[\bigcap]    | asciimath:[nnn]  | N-Ary Intersection
>| `\&#x22C3;`{bl}  `\&#8899;` | `\bigcup`    | `uuu`       |  [big]##&#8899;## | latexmath:[\bigcup]    | asciimath:[uuu]  | N-Ary Union
>| `\&#x2A00;`{bl} `\&#10752;` | `\bigodot`   |             | [big]##&#10752;## | latexmath:[\bigodot]   |                  | N-Ary Circled Dot Operator
>| `\&#x2A01;`{bl} `\&#10753;` | `\bigoplus`  |             | [big]##&#10753;## | latexmath:[\bigoplus]  |                  | N-Ary Circled Plus Operator
>| `\&#x2A02;`{bl} `\&#10754;` | `\bigotimes` |             | [big]##&#10754;## | latexmath:[\bigotimes] |                  | N-Ary Circled Times Operator
>| `\&#x2A04;`{bl} `\&#10756;` | `\biguplus`  |             | [big]##&#10756;## | latexmath:[\biguplus]  |                  | N-Ary Union Operator with Plus
>| `\&#x2A06;`{bl} `\&#10758;` | `\bigsqcup`  |             | [big]##&#10758;## | latexmath:[\bigsqcup]  |                  | N-Ary Square Union Operator
|===

* https://latex.wikia.org/wiki/Sum-class_symbol[Sum-class symbol | LaTeX Wiki | FANDOM powered by Wikia]

=== Geometric Symbols
.Geometric Symbols
[cols="5a,^.^8a,^.^4a,^.^4a,^.^4a,^.^4a,7a" separator="¦" {table_options}]
|===
3+h¦ Type                                                           3+h¦ Rendered                                                    h¦
h¦ HTML Entity                h¦ Tex Alt           h¦ AsciiMath       h¦ HTML   h¦ LaTeX                       h¦ AsciiMath          h¦ Names

>¦ `\&#x2220;` {bl} `\&#8736;` ¦ `\angle`           ¦ `/_`{bl} `angle` ¦ &#8736; ¦ latexmath:[\angle]           ¦ asciimath:[/_]      ¦ Angle
>¦ `\&#x2221;` {bl} `\&#8737;` ¦ `\measuredangle`   ¦                  ¦ &#8737; ¦ latexmath:[\measuredangle]   ¦                     ¦ Measured Angle
>¦ `\&#x2222;` {bl} `\&#8738;` ¦ `\sphericalangle`  ¦                  ¦ &#8738; ¦ latexmath:[\sphericalangle]  ¦                     ¦ Spherical Angle
>¦ `\&#x2225;` {bl} `\&#8741;` ¦ `\parallel`        ¦                  ¦ &#8741; ¦ latexmath:[\parallel]        ¦                     ¦ Parallel To
>¦ `\&#x22A5;` {bl} `\&#8869;` ¦ `\bot`             ¦ pass:a[_{vbar}_] ¦ &#8869; ¦ latexmath:[\bot]             ¦ asciimath:[_|_]     ¦ Up Tack
>¦ `\&#x25A1;` {bl} `\&#9633;` ¦                    ¦ square           ¦ &#9633; ¦                              ¦ asciimath:[square]  ¦ White Square
>¦ `\&#x25B3;` {bl} `\&#9651;` ¦ `\triangle` {bl} `\bigtriangleup`
                                                    ¦ triangle         ¦ &#9651; ¦ latexmath:[\triangle] {bl} latexmath:[\bigtriangleup]
                                                                                                                ¦ asciimath:[triangle] ¦ White Up-Pointing Triangle
>¦ `\&#x25FB;` {bl} `\&#9723;` ¦ `\Box`             ¦                  ¦ &#9723; ¦ latexmath:[\Box]             ¦                      ¦ White Medium Square
>¦ `\&#x25BD;` {bl} `\&#9661;` ¦ `\bigtriangledown` ¦                  ¦ &#9661; ¦ latexmath:[\bigtriangledown] ¦                      ¦ White Down-Pointing Triangle
|===

=== Punctuation and Ellipses

.General punctuation
[cols="6a,7a,4a,4a,14a,8a" {table_options}]
|===
2+h| Type                                  2+h| Rendered                         h|                    h|
h| HTML Entity                h| Tex alt     h| HTML    h| LaTeX                 h| Character name              h| Notes

>|  `\&#x2B9;`{bl}   `\&#697;` | `\prime`     |   &#697; | latexmath:[\prime]     | Modifier Letter Prime        |
>|  `\&#x2BA;`{bl}   `\&#698;` |              |   &#698; |                        | Modifier letter double prime |
>| `\&#x2032;`{bl}  `\&#8242;` |              |  &#8242; |                        | Prime                        |
>| `\&#x2033;`{bl}  `\&#8243;` |              |  &#8243; |                        | Double Prime                 | JIS名称: 分
>| `\&#x2034;`{bl}  `\&#8244;` |              |  &#8244; |                        | Triple Prime                 | JIS名称: 秒
>| `\&#x2035;`{bl}  `\&#8245;` | `\backprime` |  &#8245; | latexmath:[\backprime] | Reversed Prime               |
|===

.Ellipses
[cols="^.^6a,8a,^.^4a,^.^4a,17a" {table_options}]
|===
2+h| Type                               2+h| Rendered                     h|
h| HTML Entity                h| Tex Alt  h| HTML    h| LaTeX             h| Character name

>| `\&#x2026;`{bl}  `\&#8230;` | `\ldots`  |  &#8230; | latexmath:[\ldots] | Horizontal Ellipsis
>| `\&#x2236;`{bl}  `\&#8758;` |           |  &#8758; |                    | Ratio
>| `\&#x22EE;`{bl}  `\&#8942;` | `\vdots`  |  &#8942; | latexmath:[\vdots] | Vertical Ellipsis
>| `\&#x22EF;`{bl}  `\&#8943;` | `\cdots`  |  &#8943; | latexmath:[\cdots] | Midline Horizontal Ellipsis
>| `\&#x22F0;`{bl}  `\&#8944;` |           |  &#8944; |                    | Up Right Diagonal Ellipsis
>| `\&#x22F1;`{bl}  `\&#8945;` | `\ddots`  |  &#8945; | latexmath:[\ddots] | Down Right Diagonal Ellipsis
>| `\&#x2807;`{bl} `\&#10247;` |           | &#10247; |                    | Braille Pattern Dots-123
|===

.Other Punctuation
[cols="1a,2a,1a,1a,2a" {table_options}]
|===
2+h| Type                                       2+h| Rendered                             h|
h| HTML Entity                 h| Tex Alt         h| HTML    h| LaTeX                     h| Names

>| `\&#xA7;` {bl}  `\&#167;` {bl} `\&sect;`
                                | `\S`             |  &#167;  | latexmath:[\S]             | Section sign
>| `\&#x25B4;` {bl} `\&#9652;`  | `\blacktriangle` |  &#9652; | latexmath:[\blacktriangle] | Black Up-Pointing Small Triangle
|===

.References
* https://www.fileformat.info/info/unicode/block/greek_and_coptic/list.htm[Unicode Characters in the Greek and Coptic Block]
* https://ejje.weblio.jp/content/ellipses[ellipsesの意味・使い方 - 英和辞典 WEBLIO辞書]
* https://www.compart.com/en/unicode/category/Po[List of Unicode Characters of Category “Other Punctuation” - Compart]

=== Misc

.Math Symbol
[cols="1a,2a,1a,1a,2a" {table_options}]
|===
2+h| Type                               2+h| Rendered                     h|
h| HTML Entity                 h| Tex Alt h| HTML    h| LaTeX             h| Names

>|  `\&#x2118;` {bl} `\&#8472;` | `\wp`    |  &#8472; | latexmath:[\wp]    | Script Capital P (Weierstrass's elliptic functions)
>|  `\&#x221e;` {bl} `\&#8734;` | `\infty` |  &#8734; | latexmath:[\infty] | Infinity
|===

.General Symbol
[cols="1a,2a,1a,1a,2a" {table_options}]
|===
2+h| Type                                     2+h| Rendered                             h|
h| HTML Entity                 h| Tex Alt       h| HTML      h| LaTeX                   h| Names
>|  `\&#x22C4;` {bl} `\&#8472;` | `\diamond`     |    &#8900; | latexmath:[\diamond]     | Diamond Operator
>|  `\&#x2660;` {bl} `\&#9824;` | `\spadesuit`   |    &#9824; | latexmath:[\spadesuit]   | Black Spade Suit
>|  `\&#x2661;` {bl} `\&#9825;` | `\heartsuit`   |    &#9825; | latexmath:[\heartsuit]   | White Heart Suit
>|  `\&#x2662;` {bl} `\&#9826;` | `\diamondsuit` |    &#8900; | latexmath:[\diamondsuit] | White Diamond Suit
>|  `\&#x2663;` {bl} `\&#9827;` | `\clubsuit`    |    &#9827; | latexmath:[\clubsuit]    | Black Club Suit
>|  `\&#x266D;` {bl} `\&#9837;` | `\flat`        |    &#9837; | latexmath:[\flat]        | Music Flat Sign
>|  `\&#x266E;` {bl} `\&#9838;` | `\natural`     |    &#9838; | latexmath:[\natural]     | Music Natural Sign
>|  `\&#x266F;` {bl} `\&#9839;` | `\sharp`       |    &#9839; | latexmath:[\sharp]       | Music Sharp Sign
>|  `\&#x2020;` {bl} `\&#8224;` | `\dagger`      |    &#8224; | latexmath:[\dagger]      | Dagger
>|  `\&#x2021;` {bl} `\&#8225;` | `\ddagger`     |    &#8225; | latexmath:[\ddagger]     | Double Dagger
|===

.Other Symbols
[cols="1a,2a,1a,1a,2a" {table_options}]
|===
2+h| Type                                  2+h| Rendered                        h|
h| HTML Entity                 h| Tex Alt    h| HTML    h| LaTeX                h| Names

>|  `\&#x2322;` {bl} `\&#8994;` | `\frown`    |  &#8994; | latexmath:[\frown]    | Frown
>|  `\&#x2323;` {bl} `\&#8995;` | `\smile`    |  &#8995; | latexmath:[\smile]    | Smile
>|  `\&#x2572;` {bl} `\&#9586;` | `\diagdown` |  &#9586; | latexmath:[\diagdown] | Box Drawings Light Diagonal Upper Left to Lower Right
>|  `\&#x2605;` {bl} `\&#9733;` | `\bigstar`  |  &#9733; | latexmath:[\bigstar]  | Black Star
|===

.Misc
[cols="1a,2a,1a,1a,2a" {table_options}]
|===
2+h| Type                                   2+h| Rendered                         h|
h| HTML Entity                 h| Tex Alt     h| HTML    h| LaTeX                 h| Names
>|    `\&#x5c;` {bl} `\&#92;`   |              |    &#92; |                        | Reverse Solidus
>|  `\&#x2216;` {bl} `\&#8726;` | `\backslash` |  &#8726; | latexmath:[\backslash] | Set Minus
>|    `\&#x5F;` {bl} `\&#95;`   |              |    &#95; |                        | Low Line
|===
* https://asciidoctor.org/docs/user-manual/#replacements[Replacements | Asciidoctor User Manual]
